# Generated by Django 3.1.7 on 2021-03-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210328_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
    ]
