# Generated by Django 3.1.7 on 2021-04-02 09:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='BE', max_length=2),
            preserve_default=False,
        ),
    ]
