# Generated by Django 3.1.7 on 2021-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send_to',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Bag', 'Bag'), ('Trade', 'Trade')], default=1, max_length=7),
        ),
    ]
