# Generated by Django 3.1.7 on 2021-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210410_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='send_to',
        ),
    ]
