# Generated by Django 3.1.7 on 2021-04-08 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210408_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='bag_size',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='character',
            name='storage',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='bag_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='gold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='storage',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(50)]),
        ),
    ]
