# Generated by Django 3.1.7 on 2021-04-10 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_auto_20210409_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_size', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(50)])),
                ('bag_item', models.CharField(blank=True, max_length=254, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('item_size', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
