# Generated by Django 3.1.7 on 2021-04-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_auto_20210411_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name_plural': 'User owned'},
        ),
        migrations.CreateModel(
            name='UserOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('item_size', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('item_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trading',
            },
        ),
    ]
