# Generated by Django 3.1.7 on 2021-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210411_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name_plural': 'Trading'},
        ),
        migrations.AlterModelOptions(
            name='userowned',
            options={'verbose_name_plural': 'User owned'},
        ),
        migrations.AlterField(
            model_name='userowned',
            name='item',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
