# Generated by Django 3.1.7 on 2021-04-11 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210407_1224'),
        ('profiles', '0001_initial'),
        ('game', '0011_auto_20210411_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='bag_items',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='storage',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='bag_increase',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='storage_increase',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='storage_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='trade_increase',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='trade_items',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('Storage', 'Storage'), ('Bag', 'Bag'), ('Trade', 'Trade')], default='Storage', max_length=7)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='bagstorage',
            name='bag_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gameitem'),
        ),
    ]
