# Generated by Django 3.1.7 on 2021-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20210416_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='character',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
