# Generated by Django 3.1.7 on 2021-04-16 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_gameprofile_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strength', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.creed')),
            ],
        ),
        migrations.DeleteModel(
            name='CreateCharacter',
        ),
    ]
