# Generated by Django 3.1.7 on 2021-04-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('game', '0015_auto_20210416_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
