# Generated by Django 3.1.7 on 2021-04-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_character_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_profile',
            new_name='user',
        ),
    ]
