# Generated by Django 3.1.7 on 2021-04-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20210417_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='character',
            new_name='character_name',
        ),
    ]
