# Generated by Django 3.1.7 on 2021-04-17 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20210417_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagstorage',
            name='bag_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(50)]),
        ),
    ]
