# Generated by Django 3.1.7 on 2021-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20210417_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
