# Generated by Django 3.1.7 on 2021-05-03 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20210418_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='bag_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='storage_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500000), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='trade_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(50)]),
        ),
    ]
