# Generated by Django 3.1.7 on 2021-03-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
