# Generated by Django 3.1.7 on 2021-04-07 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210321_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(5.0, message=None), django.core.validators.MinValueValidator(0.0, message=None)]),
        ),
    ]
