# Generated by Django 3.1.7 on 2021-05-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_freegift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeGift',
        ),
    ]
