# Generated by Django 3.1.7 on 2021-05-07 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_freegift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(100, message=None), django.core.validators.MinValueValidator(0.0, message=None)]),
        ),
    ]
